apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-controller
  name: gitops-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-controller
  strategy: {}
  template:
    metadata:
      labels:
        app: gitops-controller
    spec:
      containers:
        - image: ghcr.io/thongdepzai-cloud/gitops-controller:latest
          name: gitops-controller
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: thongdepzai-cloud-gitops-controller
